name: palm_hills_club
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.13.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
#  splashscreen: ^1.3.50
  flutter_svg: ^0.22.0
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  carousel_slider: 4.0.0-nullsafety.0
  international_phone_input: ^1.0.4
  get: ^4.1.4
  amplify_flutter: ^0.1.5
  amplify_auth_cognito: ^0.1.5
  amplify_analytics_pinpoint: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4



flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

fonts:
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Bold.otf
          style: Bold